# This Makefile may be included from any sub-directory, provided PROJECT_HOME is
# suitably defined, in order to define the %.fst-in and %.fsti-in targets for
# computing the arguments to the interactive mode.

PROJECT_HOME ?= .

ifeq (,$(KRML_HOME))
  # assuming test/sepcomp/b
  KRML_HOME=$(CURDIR)/../../..
endif
export KRML_HOME

# I prefer to always check all fst files in the source directories; otherwise,
# it's too easy to add a new file only to find out later that it's not being
# checked. Note the usage of PROJECT_HOME
SOURCE_DIRS = $(PROJECT_HOME)

# We want our source tree on the include path, along with pre-built ulib and
# krmllib so that F* can reuse these build artifacts rather than reverify F* and
# krmllib as part of this build (which would be doomed to fail since there's a
# lot of trickery involved in building ulib -- better leave it up to the F*
# build!).
#
# Also note that we have our own directory on the include path for the sake of
# the interactive mode, for finding checked files for our own F* files.
INCLUDE_DIRS = \
  $(SOURCE_DIRS) \
  $(KRML_HOME)/krmllib \
  $(KRML_HOME)/krmllib/obj \
  $(PROJECT_HOME)/../a \
  $(PROJECT_HOME)/../a/obj \
  $(PROJECT_HOME)/obj


FSTAR_INCLUDES = $(addprefix --include ,$(INCLUDE_DIRS))

%.fst-in %.fsti-in:
	@echo $(FSTAR_INCLUDES)

